### PR TITLE
init.d script handle creation of pid direectory

### PR DESCRIPTION
**Pull request by basvandervlies**

### CODE REVIEW

**Comment by basvandervlies** [comment]
this is dependent on pull request #20

**Comment by bahamat** [comment]
I think we actually want to daemons to create the directory and pid files.

**Comment by basvandervlies** [comment]
@bahamat then we have to write  a patch for it. In debian there a a lot of init.d scripts that create this directory and not the software

**Comment by bahamat** [comment]
Ted was going to look at doing this.

**Comment by bahamat** [comment]
Can you create a new pull request for this against `master`?

**Comment by basvandervlies** [comment]
i will do

**Pull request closed without merging**
