### PR TITLE
verify_files must also use /var/log/cfengine3

### PR DESCRIPTION
**Pull request by basvandervlies**

### CODE REVIEW

**Comment by basvandervlies** [comment]
I have written a patch for cfengine core. Add a configure option '--with-logdir=/var/log/cfengine3':
- https://github.com/cfengine/core/pull/1004

**Comment by basvandervlies** [comment]
This pull request cfengine/core#1004 is now merged in cfengine master branch

**Comment by Webhuis** [comment]
Beste Bas,

Kijk ff of jij nu ook commit rechten hebt op Webhuis/Cfengine-debian?

Met vriendelijke groet,
Martin.

+31651567029

<html><body><a href="http://nl.linkedin.com/pub/martin-simons/1/b78/966"
style="text-decoration:none;"><span style="font: 80% Arial,sans-serif;
color:#0783B6;">View Martin Simons's LinkedIn profileView Martin Simons's
profile</span></a></body></html>

**Comment by basvandervlies** [comment]
Will close this one. It is replace by a more general pull request #23

**Pull request closed without merging**
