### PR TITLE
binary directory has changed to /usr/bin. Temporary fix so we have a working package

### PR DESCRIPTION
**Pull request by basvandervlies**
- https://github.com/Webhuis/Cfengine-debian/issues/29

### CODE REVIEW

**Comment by bahamat** [comment]
According to Antonio, we need to put the binaries in `/usr/sbin`. If this is temporary until we can switch to `/usr/sbin` then I'll merge it.

**Comment by zloidemon** [comment]
You be able to change symlink path to /usr/sbin

**Comment by basvandervlies** [comment]
@bahamat is this due the fact that the old package installed the binaries in /usr/sbin.  Currently there is no way to specify that the binaries should go in `sbin` directory because all cfengine configuration files and source code expects the binaries in sys.workdir/bin

**Comment by bahamat** [comment]
Superseded by #32.

**Pull request closed without merging**
