### PR TITLE
The ppkeys permission directory is wrong, see issue:

### PR DESCRIPTION
**Pull request by basvandervlies**
- https://github.com/Webhuis/Cfengine-debian/issues/28

### CODE REVIEW

**Comment by bahamat** [comment]
The default cfengine permissions, only `inputs`, `modules`, `outputs`, and `ppkeys` are mode `700`. The  permissions of the entire `$WORKDIR` should not be changed..

```
drwxr-xr-x  2 root root  4096 Aug  1 10:27 ./bin
drwx------  2 root root  4096 Oct  1 01:20 ./inputs
drwxr-xr-x  2 root root  4096 Feb 19  2013 ./lastseen
drwxr-xr-x  2 root root  4096 Aug  1 10:27 ./lib
drwxr-xr-x  2 root root  4096 Mar  4  2013 ./masterfiles
drwx------  2 root root  4096 Oct 10  2012 ./modules
drwx------  2 root root 86016 Oct 15 11:00 ./outputs
drwx------  2 root root  4096 Aug  1 00:23 ./ppkeys
drwxr-xr-x  2 root root  4096 Jul 19 15:03 ./reports
drwxr-xr-x  2 root root  4096 Sep  5 23:21 ./repository
drwxr-xr-x  2 root root  4096 Oct 15 11:00 ./state
```

I'm also not sure this will fix the error. I believe ppkeys itself is directly checked, not just the path.

**Comment by basvandervlies** [comment]
On 15 okt. 2013, at 20:05, Brian Bennett notifications@github.com wrote:

> The default cfengine permissions, only inputs, modules, outputs, and ppkeys are mode 700. The permissions of the entire $WORKDIR should not be changed..
> 
> drwxr-xr-x  2 root root  4096 Aug  1 10:27 ./bin
> drwx------  2 root root  4096 Oct  1 01:20 ./inputs
> drwxr-xr-x  2 root root  4096 Feb 19  2013 ./lastseen
> drwxr-xr-x  2 root root  4096 Aug  1 10:27 ./lib
> drwxr-xr-x  2 root root  4096 Mar  4  2013 ./masterfiles
> drwx------  2 root root  4096 Oct 10  2012 ./modules
> drwx------  2 root root 86016 Oct 15 11:00 ./outputs
> drwx------  2 root root  4096 Aug  1 00:23 ./ppkeys
> drwxr-xr-x  2 root root  4096 Jul 19 15:03 ./reports
> drwxr-xr-x  2 root root  4096 Sep  5 23:21 ./repository
> drwxr-xr-x  2 root root  4096 Oct 15 11:00 ./state
> 
> I'm also not sure this will fix the error. I believe ppkeys itself is directly checked, not just the path.

Did you purge the package and re-install it again.  I did on wheezy and jessie and then the directory looks like this:
{{{
root@deb-jessie:/var/lib/cfengine3# ls -lrt
total 28
drwxr-xr-x 2 root root 4096 Oct 15 20:50 ppkeys
drwxr-xr-x 2 root root 4096 Oct 15 20:50 outputs
drwxr-xr-x 2 root root 4096 Oct 15 20:50 modules
drwxr-xr-x 2 root root 4096 Oct 15 20:50 masterfiles
lrwxrwxrwx 1 root root   14 Oct 15 20:50 inputs -> /etc/cfengine3
lrwxrwxrwx 1 root root    9 Oct 15 20:50 bin -> /usr/sbin
drwxr-xr-x 2 root root 4096 Oct 15 20:50 state
drwxr-xr-x 2 root root 4096 Oct 15 20:50 reports
drwxr-xr-x 2 root root 4096 Oct 15 20:50 lastseen
}}}

---

SURFsara has a new telephone number: +31 20 800 1300. 

Bas van der Vlies
| Operations, Support & Development | SURFsara | Science Park 140 | 1098 XG  Amsterdam
| T +31 (0) 20 800 1300  | bas.vandervlies@surfsara.nl | www.surfsara.nl |

**Comment by basvandervlies** [comment]
or just do:
- `dpkg --contents <package>`

**Comment by bahamat** [comment]
I was using the original cfengine-community package for comparison.

Considering that inputs is a symlink, then only ppkeys, outputs and modules should be mode 700.

**Comment by basvandervlies** [comment]
@bahamat this patch fixes the ppkeys directory. We can do the other directories in a other pull request. If the package is installed the permission are wrong.

**Comment by bahamat** [comment]
Doesn't this mean that the entire WORKDIR is being changed?

```
 +    chmod 700 $WORKDIR 
```

**Comment by basvandervlies** [comment]
That Is an error ppkeys must be appended.

**Comment by bahamat** [comment]
That's where the confusion came from. I thought you were intending to change everything and I was saying you shouldn't change everything, just what's needed.

Submit an updated pull request and I'll merge it.

**Pull request closed without merging**
